package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idempresa;
     private String nombre;
     private String oficinas;
     private Date fundacion;
     private int numeroempleados;
     private String contacto;
     private String presidente;
     private Set vacantes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idempresa, String nombre, String oficinas, Date fundacion, int numeroempleados, String contacto, String presidente) {
        this.idempresa = idempresa;
        this.nombre = nombre;
        this.oficinas = oficinas;
        this.fundacion = fundacion;
        this.numeroempleados = numeroempleados;
        this.contacto = contacto;
        this.presidente = presidente;
    }
    public Empresa(int idempresa, String nombre, String oficinas, Date fundacion, int numeroempleados, String contacto, String presidente, Set vacantes) {
       this.idempresa = idempresa;
       this.nombre = nombre;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numeroempleados = numeroempleados;
       this.contacto = contacto;
       this.presidente = presidente;
       this.vacantes = vacantes;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public Date getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Date fundacion) {
        this.fundacion = fundacion;
    }
    public int getNumeroempleados() {
        return this.numeroempleados;
    }
    
    public void setNumeroempleados(int numeroempleados) {
        this.numeroempleados = numeroempleados;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }




}


