package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1



/**
 * Explaboral generated by hbm2java
 */
public class Explaboral  implements java.io.Serializable {


     private int idexplaboral;
     private Profesionista profesionista;
     private String empresa;
     private String cargo;
     private String periodo;

    public Explaboral() {
    }

    public Explaboral(int idexplaboral, Profesionista profesionista, String empresa, String cargo, String periodo) {
       this.idexplaboral = idexplaboral;
       this.profesionista = profesionista;
       this.empresa = empresa;
       this.cargo = cargo;
       this.periodo = periodo;
    }
   
    public int getIdexplaboral() {
        return this.idexplaboral;
    }
    
    public void setIdexplaboral(int idexplaboral) {
        this.idexplaboral = idexplaboral;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


