package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1



/**
 * Formacionaca generated by hbm2java
 */
public class Formacionaca  implements java.io.Serializable {


     private int idformacionaca;
     private Profesionista profesionista;
     private String colegio;
     private int grado;
     private String periodo;

    public Formacionaca() {
    }

    public Formacionaca(int idformacionaca, Profesionista profesionista, String colegio, int grado, String periodo) {
       this.idformacionaca = idformacionaca;
       this.profesionista = profesionista;
       this.colegio = colegio;
       this.grado = grado;
       this.periodo = periodo;
    }
   
    public int getIdformacionaca() {
        return this.idformacionaca;
    }
    
    public void setIdformacionaca(int idformacionaca) {
        this.idformacionaca = idformacionaca;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public int getGrado() {
        return this.grado;
    }
    
    public void setGrado(int grado) {
        this.grado = grado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


