package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1



/**
 * PostularId generated by hbm2java
 */
public class PostularId  implements java.io.Serializable {


     private int idprofesionista;
     private int idvacante;

    public PostularId() {
    }

    public PostularId(int idprofesionista, int idvacante) {
       this.idprofesionista = idprofesionista;
       this.idvacante = idvacante;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public int getIdvacante() {
        return this.idvacante;
    }
    
    public void setIdvacante(int idvacante) {
        this.idvacante = idvacante;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PostularId) ) return false;
		 PostularId castOther = ( PostularId ) other; 
         
		 return (this.getIdprofesionista()==castOther.getIdprofesionista())
 && (this.getIdvacante()==castOther.getIdvacante());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdprofesionista();
         result = 37 * result + this.getIdvacante();
         return result;
   }   


}


