package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private int idprofesionista;
     private String nombre;
     private String correo;
     private int telefono;
     private String contrasena;
     private String nacionalidad;
     private String carrera;
     private Set formacionacas = new HashSet(0);
     private Set skillses = new HashSet(0);
     private Set postulars = new HashSet(0);
     private Set explaborals = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(int idprofesionista, String nombre, String correo, int telefono, String contrasena, String nacionalidad, String carrera) {
        this.idprofesionista = idprofesionista;
        this.nombre = nombre;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasena = contrasena;
        this.nacionalidad = nacionalidad;
        this.carrera = carrera;
    }
    public Profesionista(int idprofesionista, String nombre, String correo, int telefono, String contrasena, String nacionalidad, String carrera, Set formacionacas, Set skillses, Set postulars, Set explaborals) {
       this.idprofesionista = idprofesionista;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.nacionalidad = nacionalidad;
       this.carrera = carrera;
       this.formacionacas = formacionacas;
       this.skillses = skillses;
       this.postulars = postulars;
       this.explaborals = explaborals;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Set getFormacionacas() {
        return this.formacionacas;
    }
    
    public void setFormacionacas(Set formacionacas) {
        this.formacionacas = formacionacas;
    }
    public Set getSkillses() {
        return this.skillses;
    }
    
    public void setSkillses(Set skillses) {
        this.skillses = skillses;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }
    public Set getExplaborals() {
        return this.explaborals;
    }
    
    public void setExplaborals(Set explaborals) {
        this.explaborals = explaborals;
    }




}


