package modelo;
// Generated Feb 20, 2018 2:08:15 PM by Hibernate Tools 4.3.1



/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private int idskills;
     private Profesionista profesionista;
     private String nombre;
     private int grado;

    public Skills() {
    }

    public Skills(int idskills, Profesionista profesionista, String nombre, int grado) {
       this.idskills = idskills;
       this.profesionista = profesionista;
       this.nombre = nombre;
       this.grado = grado;
    }
   
    public int getIdskills() {
        return this.idskills;
    }
    
    public void setIdskills(int idskills) {
        this.idskills = idskills;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getGrado() {
        return this.grado;
    }
    
    public void setGrado(int grado) {
        this.grado = grado;
    }




}


